Dev Further improved new language parameter
alimranahmed/LaraOCR pull request #24
Opened 2021-11-20 17:54 UTC by Henning256

Fixes # .

Changes proposed in this pull request: 
- using config file for default language setting
- implemented function supportedLanguages
- implemented function languageSupported to check if configured language is supported
@alimranahmed

2021-11-20 18:02 UTC, Henning256 commented
You gave me write access to the project. Was that intentionally?

Cheers,
Henning

2021-11-21 18:42 UTC, alimranahmed requested changes

2021-11-21 18:42 UTC, alimranahmed commented on src/Services/Tesseract.php
> +    public function languageSupported($lang)
I preffer to use `is` or `has` prefix for methods that return boolean value. So, my recommended method name for this one will be `isLanguageSupported($lang)`

2021-11-21 18:45 UTC, alimranahmed commented
@Henning256 
Well, this is an open source package and you can always send PR whenever you think you can improve this package. I merged your last PR which is not write acess to be exact. But yeah, your contribution is now in this repository. 

Hope to merge this PR soon too.

2021-11-21 20:42 UTC, merged